POST http://localhost:5000/api/users/create
Content-Type: application/json

{
    "userEmail": "phsang49@gmail.com",
    "userPassword": "phsang49@gmail.com",
    "userPossition": "Staff"
}
####
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "userEmail": "phsang49@gmail.com",
    "userPassword": "phsang49@gmail.com"
}

#####
PUT http://localhost:5000/api/auth/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTBiYTJlZGM2NWMyMjM2NzgwZTZhNzkiLCJ1c2VyRW1haWwiOiJzdGFmZkBnbWFpbC5jb20iLCJ1c2VyUG9zaXRpb24iOiJTdGFmZiIsImlhdCI6MTYyODMyNjY2Nn0.25weLR9ncoPEdcm1XQQlWkBOE9yFLWpcphrAXYz1ZRc

{
    "userName": "Staff Aisa_Park",
    "userBirthday": "2001-09-04T00:00:00.155+00:00",
    "userAddress": "Ngũ Hành Sơn, Đà Nẵng, Việt Nam",
    "userPassword": "staff@gmail.com",
    "userNewPassword": ""
}

#####
GET http://localhost:5000/api/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTBiYTI4MGM2NWMyMjM2NzgwZTZhNzUiLCJ1c2VyRW1haWwiOiJwaHNhbmc0OUBnbWFpbC5jb20iLCJ1c2VyUG9zaXRpb24iOiJNYW5hZ2VyIiwiaWF0IjoxNjI4MzQyNzg4fQ.czLhj5tllpfDhBNeJM7bvylVzwBJ0ohJTgouR3cPMuk

####
POST http://localhost:5000/api/Page/update
Content-Type: application/json

{
    "userEmail": "phsang48@gmail.com",
    "userPassword": "1234e5",
    "userPossition": "Staff"
}
####
POST http://localhost:5000/api/Ports/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTBiYTI4MGM2NWMyMjM2NzgwZTZhNzUiLCJ1c2VyUG9zaXRpb24iOiJNYW5hZ2VyIiwiaWF0IjoxNjI4MjM1NjczfQ.KREz_SMY79_LisLJlUydBcnxDFNtxU1yRXIPmEFQAFo

{
    "portName": "Tàu Vũ Trụ",
    "portDescription": "Trải nghiệm cảm giác không giới hạn mà bạn không thể thử ở bất cứ đâu trong thành phố này.",
    "portStatus": true
}
####
GET http://localhost:5000/api/Ports/view
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTBiYTI4MGM2NWMyMjM2NzgwZTZhNzUiLCJ1c2VyUG9zaXRpb24iOiJNYW5hZ2VyIiwiaWF0IjoxNjI4MjM1NjczfQ.KREz_SMY79_LisLJlUydBcnxDFNtxU1yRXIPmEFQAFo


######
PUT http://localhost:5000/api/Ports/update/610ba686c65c2236780e6a83
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTBiYTI4MGM2NWMyMjM2NzgwZTZhNzUiLCJ1c2VyRW1haWwiOiJwaHNhbmc0OUBnbWFpbC5jb20iLCJ1c2VyUG9zaXRpb24iOiJNYW5hZ2VyIiwiaWF0IjoxNjI4MzE4MjA2fQ.TYndxZtTQVL3qx2CHwl7a0-GvBHDhJCmZxTevnpkK3M

{
    "portName":"Vòng quay Mặt Trời",
    "portDescription": "Top 5 vòng quay cao nhất thế giới",
    "portStatus": false
}
######
GET http://localhost:5000/api/Ports/view/610ba6d2c65c2236780e6a87
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTBiYTI4MGM2NWMyMjM2NzgwZTZhNzUiLCJ1c2VyUG9zaXRpb24iOiJNYW5hZ2VyIiwiaWF0IjoxNjI4MjM1NjczfQ.KREz_SMY79_LisLJlUydBcnxDFNtxU1yRXIPmEFQAFo


######
DELETE http://localhost:5000/api/Ports/delete/610ba6d2c65c2237780e6a87
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTBiYTI4MGM2NWMyMjM2NzgwZTZhNzUiLCJ1c2VyUG9zaXRpb24iOiJNYW5hZ2VyIiwiaWF0IjoxNjI4MjM1NjczfQ.KREz_SMY79_LisLJlUydBcnxDFNtxU1yRXIPmEFQAFo

######
PUT http://localhost:5000/api/Users/update/610ba2edc65c2236780e6a79
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTBiYTI4MGM2NWMyMjM2NzgwZTZhNzUiLCJ1c2VyRW1haWwiOiJwaHNhbmc0OUBnbWFpbC5jb20iLCJ1c2VyUG9zaXRpb24iOiJNYW5hZ2VyIiwiaWF0IjoxNjI4MzQ0MTU3fQ.79gWjvFPkB_ufTb8WhvK29BpR96xJY6YwW_Gqg4q4Bk

{
    "userPosition" : "Staff",
    "userStatus": "true"
}

######
GET http://localhost:5000/api/Users/view/610ba2edc65c2236780e6a79
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTBiYTI4MGM2NWMyMjM2NzgwZTZhNzUiLCJ1c2VyRW1haWwiOiJwaHNhbmc0OUBnbWFpbC5jb20iLCJ1c2VyUG9zaXRpb24iOiJNYW5hZ2VyIiwiaWF0IjoxNjI4MzQ0MTU3fQ.79gWjvFPkB_ufTb8WhvK29BpR96xJY6YwW_Gqg4q4Bk

######
GET http://localhost:5000/api/Users/view
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTBiYTI4MGM2NWMyMjM2NzgwZTZhNzUiLCJ1c2VyRW1haWwiOiJwaHNhbmc0OUBnbWFpbC5jb20iLCJ1c2VyUG9zaXRpb24iOiJNYW5hZ2VyIiwiaWF0IjoxNjI4MzQ0MTU3fQ.79gWjvFPkB_ufTb8WhvK29BpR96xJY6YwW_Gqg4q4Bk


######
PUT http://localhost:5000/api/Page/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTBiYTI4MGM2NWMyMjM2NzgwZTZhNzUiLCJ1c2VyRW1haWwiOiJwaHNhbmc0OUBnbWFpbC5jb20iLCJ1c2VyUG9zaXRpb24iOiJNYW5hZ2VyIiwiaWF0IjoxNjI4MzQ0MTU3fQ.79gWjvFPkB_ufTb8WhvK29BpR96xJY6YwW_Gqg4q4Bk

{
    "pageStatus" : "true"
}